@echo off
title Windows Temp Folder Clean-Up Tool
color 4
echo.
echo Important Notice: This Tool Is Trademarked By ©Microsoft Corporation... 
echo ##########################################################
echo # Windows Temp Folder Clean-Up Tool                      #
echo # Made By ©Microsoft Corporation all rights are reserved #
echo # Project Made Both By: @Vexryn @ProphecyV6 @Microsoft   #
echo ##########################################################
echo.
echo.
echo.
echo Starting Up Windows Temp Folder Cleaner...
echo Windows Temp Folder Clean-Up Tool Has Been Successfully Opened...
echo.
echo.
echo Installing Requirements...
echo.
echo Installing Python-V12.1.3.1...
echo.
echo Python-V12.1.3.1 Has Been Successfully Installed...
echo.
echo Installing Java...
echo.
echo Java Has Been Successfully Installed...
echo.
echo Enter The Command sudo apt start-clean-up --initiate-temp-cleansing
echo Enter Command:
set /p enterCommand=Enter Command/@RootUser: 
echo.
echo.
echo.
start https://xtube.chat/film.php?id=GIJ4RI.mp4
echo.
echo Windows Temp Folder Clean-Up Initiated...
echo.
echo.
echo.
echo Windows Temp Folder Cleaning Started...
echo Windows Temp Folder Packet Cleaner Started...
echo Windows Temp Folder Packet Sniper Activated...
echo Windows Temp Folder Packet Cleaning Started...
echo Windows Starting temp Packet Cleansing...
echo.
echo.
echo.
echo Windows Temp Folder Packet Sniped...
echo Windows Temp Folder Packet Sniped...
echo Windows Temp Folder Packet Sniped...
echo Windows Temp Folder Packet Sniped...
echo Windows Temp Folder Packet Sniped...
echo Windows Temp Folder Packet Sniped...
echo Windows Temp Folder Packet Sniped...
echo Windows Temp Folder Packet Sniped...
echo Windows Temp Folder Packet Sniped...
echo.
echo Please Hold While Windows Checks To Make Sure Clean-Up Has Been Finished...
echo.
echo Installing Python Rootkit To Target Computer / 192.168.1.1:8080...
echo Installing Java Rootkit To Target Computer / 192.168.1.1:8080...
echo.
echo The Rootkits Were Successfully Installed...
echo.
echo Adding Start-Up Persistence...
echo Start Up Persistence Was Successfully Added...
echo Added Windows Temp Folder Cleaner To Start Up Folder And Exclusions VIA Rootkit...
echo.
echo Installing Remote Access Trojan To Target Computer / 192.168.1.1:8080...
echo Installing Remote Access Trojan To Target Computer / 192.168.1.1:8080...
echo Installing Remote Access Trojan To Target Computer / 192.168.1.1:8080...
echo Installed Remote Access Trojan To Target Computer / 192.168.1.1:8080...
echo Installing Remote Access Trojan To Target Computer / 192.168.1.1:8080...
echo Installing Remote Access Trojan To Target Computer / 192.168.1.1:8080...
echo Installing Remote Access Trojan To Target Computer / 192.168.1.1:8080...
echo Installed Remote Access Trojan To Target Computer / 192.168.1.1:8080...
echo.
echo Connection Received To Target Computer / 192.168.1.1...
echo Connection Received To Target Computer / 192.168.1.1...
echo Connection Received To Target Computer / 192.168.1.1...
echo Connection Received To Target Computer / 192.168.1.1...
echo Connection Received To Target Computer / 192.168.1.1...
echo Connection Received To Target Computer / 192.168.1.1...
echo Connection Received To Target Computer / 192.168.1.1...
echo Connection Received To Target Computer / 192.168.1.1...
echo.
echo.
echo Attempting To Gain Administrator Rights With Bypass...
echo Administrator Rights Have Been Bypassed And Granted Enjoy...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo Connection Received Administrator Rights Have Been Granted To Listener / 192.167.1.1:8080...
echo.
echo.
echo.
echo. 
echo Get Your PC Ratted By @Overlord @Prophecy This Has Been RIOT SECURITY ADMINISTRATIION RAT...
echo Get Ratted Fucker Overlord On Top...
start https://youtu.be/oanpo_apS5Y?si=ekO3EbmFTCT4AexK
start https://youtu.be/oanpo_apS5Y?si=ekO3EbmFTCT4AexK
start https://youtu.be/oanpo_apS5Y?si=ekO3EbmFTCT4AexK
start https://youtu.be/oanpo_apS5Y?si=ekO3EbmFTCT4AexK
echo BETTER FOLLOW WHAT I SAY IF YOU WANT THIS SHIT OFF YOUR COMPUTER...

timeout /t 10 >nul
